# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ main ]  # 推送 main 分支时触发，或改为 release: types: [published] 只在发布版本时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境打包 EXE

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 匹配您的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装您的依赖
        pip install pyinstaller  # 安装 PyInstaller

    - name: Build EXE
      run: |
        pyinstaller ./JsonDataComparison_test2.spec  # 使用您的 .spec 文件打包（或直接 pyinstaller --onefile main.py）

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: JSON Data Comparison  # 工件名称
        path: dist/*.exe  # EXE 输出路径（PyInstaller 默认在 dist/）
